[platformio]
default_envs = pico

[common]
build_flags = 
    -Os
    -Dtimegm=mktime
    -DDEBUG=0
    -lc -lm                       ; Importante per i colleghi (math & C libs)
    -I include
    # --- FIX CRITICI PER COMPILAZIONE PICO + FASTLED ---
    -DFASTLED_INTERNAL
    -DFASTLED_NO_CUSTOM_RED_BLACK_TREE
    -DFASTLED_RP2040_CLOCKLESS_PIO
    -DSERIAL_MAX_SETUP_TIME=5000  ; Risolve l'errore nel main.cpp
    # ---------------------------------------------------
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_RTTI
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS

[env]
framework = arduino
monitor_speed = 115200            ; Compatibile con TinyUSB
monitor_port = /dev/ttyACM?       ; Wildcard per Linux/Mac
lib_deps = 
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit GFX Library @ ^1.12.5
    adafruit/Adafruit SSD1306 @ ^2.5.16
    adafruit/Adafruit NeoPixel @ ^1.15.4
    # Usiamo la 3.9.4: supporta il Pico (PIO) ma non ha i bug della 3.10
    fastled/FastLED @ 3.9.4

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git@1.18.0
board = pico
board_build.core = earlephilhower
board_build.usb_stack = tinyusb
board_build.filesystem = fatfs
board_build.filesystem_size = 0.5m
board_build.maximum_size = 2097152
build_flags = ${common.build_flags}
upload_protocol = picotool

platform_packages = 
    # Manteniamo il toolchain specifico per Earle Philhower per evitare conflitti di linker
    toolchain-rp2040-earlephilhower
    earlephilhower/tool-mklittlefs-rp2040-earlephilhower@^5.100300.230216
