; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = pico

[env]
framework = arduino
monitor_speed = 9600
lib_deps =
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit GFX Library @ ^1.12.4
    adafruit/Adafruit SSD1306 @ ^2.5.16
    adafruit/Adafruit Neopixel @ ^1.15.2
    fastled/FastLED @ ^3.10.3
    ; Nota: rw0402/littlefs RIMOSSA. Usa LittleFS.h inclusa nel core.

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git@1.18.0
board = nanorp2040connect
board_build.core=earlephilhower
board_build.filesystem_size = 65536 ; 64KBytes
upload_protocol = picotool

platform_packages = 
    platformio/toolchain-gccarmnoneeabi
    platformio/framework-arduino-mbed
    earlephilhower/tool-mklittlefs-rp2040-earlephilhower@^5.100300.230216
