; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
build_flags = -Os
    -std=c99
	-Dtimegm=mktime
	-DDEBUG=0
	-lc -lm
	-I include
	;-D USE_TINYUSB ; Uses tinyUSB stack instead of pico-sdk
	-D CFG_TUSB_MCU=OPT_MCU_RP2040
monitor_port = /dev/ttyACM?

[platformio]
default_envs = pico

[env]
build_flags = ${common.build_flags}
framework = arduino
monitor_speed = 9600
lib_deps = 
	adafruit/Adafruit BusIO @ ^1.17.4
	adafruit/Adafruit GFX Library @ ^1.12.4
	adafruit/Adafruit SSD1306 @ ^2.5.16
	adafruit/Adafruit Neopixel @ ^1.15.2
	fastled/FastLED @ ^3.10.3

[env:pico]
build_flags = ${common.build_flags}
platform = https://github.com/maxgerhardt/platform-raspberrypi.git@1.18.0
board = pico
board_build.core = earlephilhower
board_build.filesystem_size = 65536
board_build.maximum_size = 2097152
upload_protocol = picotool
platform_packages = 
	platformio/toolchain-gccarmnoneeabi
	platformio/framework-arduino-mbed
    ;earlephilhower/tool-mklittlefs-rp2040-earlephilhower@^5.100300.230216
