[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pcb_tool"
version = "0.1.0"
dependencies = [
    "requests",
    "rich",
    "pytest",
    "requests-mock"
]

[project.scripts]
pcb-sync = "pcb_tool.main:main"
[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
    "pytest-cov",
    "flake8",
]
