[platformio]
default_envs = pico
src_dir = .
include_dir = include
build_dir = .firm-build/build
libdeps_dir = .firm-build/libdeps

[common]
build_flags = 
    -Os
    -lc -lm
    # Forza la macro ma ignora l'errore se è già definita
    -D FASTLED_INTERNAL
    -Wno-builtin-macro-redefined
    -Wno-attributes
    # --- Altri flag ---
    -D FASTLED_RP2040_CLOCKLESS_PIO
    -D FASTLED_NO_CUSTOM_RED_BLACK_TREE
    -D timegm=mktime
    -D SERIAL_MAX_SETUP_TIME=5000
    -D PROJ_NAME='"ppse-firmware"'
    -D PROJ_VERSION='"${sysenv.VERSION}"'

[env]
framework = arduino
monitor_speed = 115200
# Colora l'output del monitor seriale (ANSI)
monitor_filters = colorize, time, send_on_enter
lib_deps = 
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit GFX Library @ ^1.12.5
    adafruit/Adafruit SSD1306 @ ^2.5.16
    adafruit/Adafruit NeoPixel @ ^1.15.4
    fastled/FastLED @ 3.9.4

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
board_build.core = earlephilhower
board_build.usb_stack = tinyusb
board_build.filesystem = fatfs
board_build.filesystem_size = 0.5m
board_build.maximum_size = 2097152
build_src_filter = +<main.cpp> +<src/*.cpp>
build_flags = ${common.build_flags}
upload_protocol = picotool

# --- UX: Barre di caricamento e pulizia ---
# Forza l'output colorato anche se non rileva un terminale interattivo (utile per CI)
build_unflags = -fno-color-diagnostics
