[platformio]
default_envs = pico
# Teniamo la root come base
src_dir = .
include_dir = include
build_dir = .firm-build/build
libdeps_dir = .firm-build/libdeps

[common]
build_flags = 
    -Os -lc -lm
    -D FASTLED_INTERNAL
    -Wno-builtin-macro-redefined
    -Wno-attributes
    -D FASTLED_RP2040_CLOCKLESS_PIO
    -D FASTLED_NO_CUSTOM_RED_BLACK_TREE
    -D timegm=mktime
    -D SERIAL_MAX_SETUP_TIME=5000
    -D PROJ_NAME='"ppse-firmware"'
    -D PROJ_VERSION='"1.0.0"'
    # Path corretti per gli header
    -I include
    -I lib/minmea

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.usb_stack = tinyusb

# --- MODIFICA QUI ---
board_build.filesystem = littlefs
# --------------------

board_build.filesystem_size = 0.5m
board_build.maximum_size = 2097152

lib_deps = 
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit GFX Library @ ^1.12.5
    adafruit/Adafruit SSD1306 @ ^2.5.16
    adafruit/Adafruit NeoPixel @ ^1.15.4
    fastled/FastLED @ 3.9.4

build_src_filter = 
    +<src/main.cpp>
    +<src/core/*.cpp>
    +<src/drivers/*.cpp>
    +<src/ui/*.cpp>
    +<src/ui/views/*.cpp>
    +<src/pipeline/*.cpp>
    +<lib/minmea/minmea.c>

build_flags = ${common.build_flags}
upload_protocol = picotool
monitor_speed = 115200
