name: Firmware CI

on:
  push:
    paths: [ 'firm/**', 'build/**', 'Makefile' ]
  pull_request:
    branches: [ main ]

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck
          pip install platformio

      - name: Build Firmware
        run: make build

      - name: Quality Check
        run: make check
