name: Firmware Build Check

on:
  push:
    branches: [ '**' ]
    paths: [ 'firm/**', 'Makefile', 'build/**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/.cache
            ~/.platformio/packages
            ~/.platformio/platforms
            firm/.firm-build/libdeps
          key: ${{ runner.os }}-pio-v1-${{ hashFiles('**/platformio.ini') }}

      - name: Install Tools
        run: |
          pip install -U platformio
          sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Run Lint & Compile
        # Usa i target del tuo Makefile per coerenza
        run: |
          make fw-lint
          make build

      - name: Upload Temporary Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-preview-${{ github.sha }}
          path: firm/.firm-build/build/pico/firmware.uf2
          retention-days: 3
